from .cnaes.model import CNAE
from .empresas.model import Empresa
from .estabelecimentos.model import Estabelecimento
from .faixas_etarias.model import FaixaEtaria
from .matrizes_filiais.model import MatrizFilial
from .motivos.model import Motivo
from .municipios.model import Municipio
from .naturezas_juridicas.model import NaturezaJuridica
from .paises.model import Pais
from .portes_empresas.model import PorteEmpresa
from .qualificacoes.model import Qualificacao
from .situacoes_cadastrais.model import SituacaoCadastral
from .versionamentos.model import Versionamento