from .cnaes.model import CNAE
from .contatos.model import Contato
from .empresas.model import Empresa
from .estabelecimentos.model import Estabelecimento
from .faixas_etarias.model import FaixaEtaria
from .logradouros.model import Logradouro
from .matrizes_filiais.model import MatrizFilial
from .motivos.model import Motivo
from .municipios.model import Municipio
from .naturezas_juridicas.model import NaturezaJuridica
from .paises.model import Pais
from .portes_empresas.model import PorteEmpresa
from .qualificacoes.model import Qualificacao
from .representantes_legais.model import Representante
from .simples_nacional.model import Simples
from .situacoes_cadastrais.model import SituacaoCadastral
from .socios.model import Socio
from .usuarios.model import Usuario
from .versionamentos.model import Versionamento